### PR TITLE
Adding live stream streamfield block

### PR DESCRIPTION
**Pull request by nicklee**
BE ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2362

FR ticket: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2427

### CODE REVIEW

**Comment by nicklee** [comment]
Waiting on cloud_hosted_player_library_url from client

**Comment by richbrennan** [comment]
Needs DB migrations once all pages that need the player have been confirmed: https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2427#update-69131135

**Comment by richbrennan** [comment]
Migrations added

**Comment by nicklee** [comment]
When you have as sec could you review the front-end stuff in here @chris-lawton ?

Screenshot 2022-02-02 at 10 26 00
Screenshot 2022-02-02 at 10 25 53

Dev URL: https://rca-development.herokuapp.com/pattern-library/render-pattern/patterns/pages/guide/guide.html

**Review by victoriachan — APPROVED** [review]
LGTM

**Review by chris-lawton — APPROVED** [review]

**Comment by chris-lawton** [comment]
Looks good @nicklee!

**Pull request merged**
