### PR TITLE
Add birdbath

### PR DESCRIPTION
**Pull request by tomusher**
Adds birdbath support

### CODE REVIEW

**Comment by kevinhowbrook** [comment]
@tomusher After installing locally and running pip install and migrating, running `run_birdbath` throws:

```
ModuleNotFoundError: No module named 'birdbath.checks.heroku'
```

**Comment by tomusher** [comment]
Oops thank you - I've fixed those paths and disabled the checks in the development settings.

**Comment by kevinhowbrook** [comment]
> Oops thank you - I've fixed those paths and disabled the checks in the development settings.

Cheers, trying this out again locally. I've got to the error:

```
ImportError: Module "birdbath.checks.contrib.heroku" does not define a "AnomymisationAllowedCheck" attribute/class
```

I checked what's expected here https://git.torchbox.com/internal/django-birdbath/-/blob/master/birdbath/checks/contrib/heroku.py and in the pypi readme and it looks like locally you need to set some env vars, that should match, so I added:

```
export ALLOWS_ANONYMISATION=rca-staging
export HEROKU_APP_NAME=rca-staging
```

**Comment by tomusher** [comment]
I've fixed the name of that check.

**Comment by kevinhowbrook** [comment]
Fixed a typo and runs good locally - Thanks @tomusher I'll merge this tomorrow AM

**Pull request merged**
