### PR TITLE
#2512 & #2506 » Alumni link

### PR DESCRIPTION
**Pull request by nicklee**
New link in programme alumni panel

[FE Ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2512)

[BE Ticket](https://projects.torchbox.com/projects/rca-django-cms-project/tickets/2506)

### Screenshots

<details>
  <summary>Admin</summary>

image

</details>

<details>
  <summary>Template</summary>

image

</details>

### CODE REVIEW

**Comment by nicklee** [comment]
> Looks good, thanks. Just a question about the commit history on this

I was confused too, it seems the integration branch wasn't created with the most up-to-date master, so these commits ended up in here. 

The latest master commits have been merged into the integration branch, so i'm not sure why they are still appearing here?!

**Comment by engineervix** [comment]
Perhaps rebasing this branch onto the integration branch if this isn't already done.

**Comment by nicklee** [comment]
I rebased and seem to have messed it up even more…

so i've created a new branch and cherry picked the changes here, which seems to be looking better…:
https://github.com/torchbox/rca-wagtail-2019/pull/947

**Comment by engineervix** [comment]
> I rebased and seem to have messed it up even more…
> 
> so i've created a new branch and cherry picked the changes here, which seems to be looking better…: #947

Closed in favour of #947

**Pull request closed without merging**
